import Veil

/-!
# Regression: failed declarations block specification finalization

Lean can recover from a command elaboration error, and `#guard_msgs` deliberately
does so in batch tests. A failed Veil declaration must remain visible to
`#gen_spec`; otherwise finalization silently assembles and verifies a weaker
specification with the failed declaration omitted.
-/

set_option linter.unusedVariables false

veil module FailedDeclarationFinalization

individual flag : Bool

/-- error: unable to extract type from binder failed to pretty print term (use 'set_option pp.rawOnError true' for raw representation) -/
#guard_msgs in
relation omitted {badBinder : Bool}

#gen_state

after_init { flag := false }

action keep { flag := false }

invariant [valid] flag = false

/-- error: Unbound uncapitalized variable: nonexistent_pred -/
#guard_msgs in
invariant [broken] nonexistent_pred flag

/-- error: Cannot finalize Veil module FailedDeclarationFinalization: 2 Veil declarations failed to elaborate. -/
#guard_msgs in
#gen_spec

end FailedDeclarationFinalization

veil module FailedGeneratedDeclarationFinalization

-- Force the class generated by the enum elaborator to collide with an
-- existing user declaration.
def CollidingEnum_EnumClass := Unit

/-- error: `FailedGeneratedDeclarationFinalization.CollidingEnum_EnumClass` has already been declared -/
#guard_msgs in
enum CollidingEnum = {value}

/-- error: Cannot finalize Veil module FailedGeneratedDeclarationFinalization: 1 Veil declaration failed to elaborate. -/
#guard_msgs in
#gen_spec

end FailedGeneratedDeclarationFinalization
